version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "9090:80"
    volumes:
      - "../src:/var/www/html/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php-fpm
      - db

  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - "../src:/var/www/html/"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql-data:/var/lib/mysql"
